# Generated by Django 5.2.13 on 2026-04-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('destination', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourCostScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('num_pax', models.PositiveIntegerField()),
                ('num_tour_leaders', models.PositiveIntegerField(default=0)),
                ('num_vehicles', models.PositiveIntegerField(default=0)),
                ('selling_price_per_pax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='THB', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_scenarios', to='tours.tour')),
            ],
            options={
                'ordering': ['num_pax'],
            },
        ),
        migrations.CreateModel(
            name='TourCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('insurance', 'Insurance'), ('visa', 'Visa'), ('miscellaneous', 'Miscellaneous'), ('management_fee', 'Management Fee'), ('op_ticket', 'Op Ticket'), ('op_expense', 'Op Expense'), ('accommodation', 'Accommodation'), ('activity', 'Activity'), ('transportation', 'Transportation'), ('other', 'Other')], max_length=30)),
                ('pay_to', models.CharField(blank=True, default='', max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tours.tourcostscenario')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='TourExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='tours.tour')),
            ],
            options={
                'unique_together': {('tour', 'currency_code')},
            },
        ),
    ]
