# Generated by Django 5.2.13 on 2026-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourcostscenario',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='tourcostitem',
            name='markup_percent',
        ),
        migrations.RemoveField(
            model_name='tourcostscenario',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tourcostscenario',
            name='num_vehicles',
        ),
        migrations.AddField(
            model_name='tourcostitem',
            name='cost_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared')], default='personal', max_length=10),
        ),
        migrations.AddField(
            model_name='tourcostitem',
            name='currency',
            field=models.CharField(default='THB', max_length=10),
        ),
        migrations.AddField(
            model_name='tourcostscenario',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
