# Generated by Django 5.2.13 on 2026-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourcostscenario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcostitem',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
