# Generated by Django 5.2.13 on 2026-04-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_add_is_synced_to_cost_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcostitem',
            name='is_synced',
            field=models.BooleanField(default=True),
        ),
    ]
