# Generated by Django 5.2.13 on 2026-04-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_change_is_synced_default_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourcostitem',
            name='cost_type',
        ),
        migrations.RemoveField(
            model_name='tourcostitem',
            name='quantity',
        ),
    ]
