# Generated by Django 5.2.13 on 2026-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_tourcostitem_cost_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcostscenario',
            name='is_desired',
            field=models.BooleanField(default=False),
        ),
    ]
