# Generated by Django 5.2.13 on 2026-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('staff', 'Staff'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
    ]
